# Continuous integration handling for GitHub Actions workflows
name: ci-github-actions

on:
  pull_request:
    paths:
      - .github/workflows/*.yml

permissions:
  contents: read

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
        with:
          go-version-file: 'go.mod'
      - run: go install github.com/rhysd/actionlint/cmd/actionlint@latest
      - run: actionlint
